### PR TITLE
Add new GraniteUI validator: wcmio.handler.media.mediaFormat

### PR DESCRIPTION
**Pull request by stefanseifert**
Add new GraniteUI validator `wcmio.handler.media.mediaFormat` which can be set on Media Handler File Upload or Path Field components to hook the media format validation into the GraniteUI dialog validation.

Example:
```json
"mediaRef": {
  "sling:resourceType": "wcm-io/handler/media/components/granite/form/fileupload",
  "fieldLabel": "Asset reference",
  "validation": ["wcmio.handler.media.mediaFormat"]
}
```

Fixes #68

### CODE REVIEW

**Comment by srigurram7792** [comment]
Hi @stefanseifert  is there any ETA for this topic? we would like to use this feature going forward in our project. Thanks

**Comment by stefanseifert** [comment]
with upcoming adaptTo() i have very little time currently, i plan to finish this in november

**Comment by srikanthgurram-17** [comment]
Hi @stefanseifert , any updates here?

**Comment by stefanseifert** [comment]
@srikanthgurram-17 it should work now if configured as described in the issue description.
can you give it a try?

**Comment by srikanthgurram-17** [comment]
> @srikanthgurram-17 it should work now if configured as described in the issue description. can you give it a try?

@stefanseifert I verified in my local looks fine. Thanks

**Comment by srikanthgurram-17** [comment]
Hey @stefanseifert  is there a plan to release this feature, I see the release of media handler not yet done. can we expect this soon ?

**Comment by stefanseifert** [comment]
i will release it early next week

**Pull request merged**
